let products = [
  {
    id: 0,
    name: 'Crystal Titan VR5 1TB - 6G',
    price: 21990,
    rating: 4,
    amount: 0,
    memory: 1000,
    network: '6g',
    img: {
      url: 'assets/img/Crystal_Titan_VR5.webp',
      width: 1000,
      height: 450,
      alt: 'Gaming phone Crystal Titan VR5',
    },
  },
  {
    id: 1,
    name: 'Cyber Core X1 512GB - 6G',
    price: 17990,
    rating: 3.5,
    amount: 0,
    memory: 512,
    network: '6g',
    img: {
      url: 'assets/img/CyberCore_X1.webp',
      width: 1000,
      height: 450,
      alt: 'Gaming phone Cyber Core X1',
    },
  },
  {
    id: 2,
    name: 'Eclipse Nova X3 512GB - 6G',
    price: 16490,
    rating: 4.5,
    amount: 0,
    memory: 512,
    network: '6g',
    img: {
      url: 'assets/img/Eclipse_Nova_X3.webp',
      width: 1000,
      height: 450,
      alt: 'Gaming phone Eclipse Nova X3',
    },
  },
  {
    id: 3,
    name: 'Galaxy Warlord T8 512GB - 6G',
    price: 16990,
    rating: 4,
    amount: 0,
    memory: 512,
    network: '6g',
    img: {
      url: 'assets/img/Galaxy_Warlord_T8.webp',
      width: 1000,
      height: 450,
      alt: 'Gaming phone Galaxy Warlord T8',
    },
  },
  {
    id: 4,
    name: 'Inferno Fold G5 1TB - 6G',
    price: 23490,
    rating: 5,
    amount: 0,
    memory: 1000,
    network: '6g',
    img: {
      url: 'assets/img/Inferno_Fold_G5.webp',
      width: 1000,
      height: 450,
      alt: 'Gaming phone Inferno Fold G5',
    },
  },
  {
    id: 5,
    name: 'Neo Arcadia Q7 1TB - 6G',
    price: 25990,
    rating: 4.5,
    amount: 0,
    memory: 1000,
    network: '6g',
    img: {
      url: 'assets/img/Neo_Arcadia_Q7.webp',
      width: 1000,
      height: 450,
      alt: 'Gaming phone Neo Arcadia Q7',
    },
  },
  {
    id: 6,
    name: 'Phantom Blade X2 128GB - 5G',
    price: 14690,
    rating: 3.5,
    amount: 0,
    memory: 128,
    network: '5g', // Lägg till nätverksinformation
    img: {
      url: 'assets/img/Phantom_Blade_X2.webp',
      width: 1000,
      height: 450,
      alt: 'Gaming phone Phantom Blade X2',
    },
  },
  {
    id: 7,
    name: 'Quantum Edge Y9 1TB - 5G',
    price: 14990,
    rating: 3,
    amount: 0,
    memory: 1000,
    network: '5g',
    img: {
      url: 'assets/img/Quantum_Edge_Y9.webp',
      width: 1000,
      height: 450,
      alt: 'Gaming phone Quantum Edge Y9',
    },
  },
  {
    id: 8,
    name: 'Shadow Strike Z1 256GB - 5G',
    price: 13990,
    rating: 2.5,
    amount: 0,
    memory: 256,
    network: '5g',
    img: {
      url: 'assets/img/Shadow_Strike_Z1.webp',
      width: 1000,
      height: 450,
      alt: 'Gaming phone Shadow Strike Z1',
    },
  },
  {
    id: 9,
    name: 'Vortex GX9 256GB - 5G',
    price: 13290,
    rating: 3,
    amount: 0,
    memory: 256,
    network: '5g',
    img: {
      url: 'assets/img/Vortex_GX9.webp',
      width: 1000,
      height: 450,
      alt: 'Gaming phone Vortex GX9',
    },
  },
]

export default products
